language: java
jdk:
  - oraclejdk7

script: "mvn package"

after_success:
# password="pwd"
  - secure: "L8GLJKivjpIoKJZtkxy4gjVXrNOpC1hKfpP38UBwPMX6CW03lZ/aGp3um1KQ3ZUTbRQZTXP0J8Ya6XsS/UIbf8ROSg3uX96IUUKiU3CLDyaGee6UtvZFcmCYBZ65QhXmPOfYLM5uswy76941iLSKrNyJs+tJJ8K8+GLAiR+syko="
# encrypt -> openssl aes-256-cbc -k "pwd" -in id_rsa -out id_rsa.enc -a
# decrypt -> openssl aes-256-cbc -k "pwd" -in deploy_key.enc -d -a -out id_rsa
  - openssl aes-256-cbc -k "$password" -in deploy_key.enc -d -a -out id_rsa
# scp copy -> scp -i ./id_rsa -o StrictHostKeyChecking=no target/tapcat-webserver.war tapcat@somehost.net:/home/tapcat/
  - scp -i ./id_rsa -o StrictHostKeyChecking=no target/tapcat-webserver.war tapcat@api.tapcat.net:/home/tapcat/
