language: java
jdk:
  - oraclejdk7

env:
  global:
    # PASSWORD=pwd
    secure: "PHqSWHyJolGphXMAiUJ3QNUzAUMC80tlWwVQcdV+myfC0Ovi3naKoty7KfKl2KtGamLKjwCBc8ujRm2ayoL6KM1hGLmp1IUc80uzI8h4QLrx7ky8TYvmXvw/hF9euMCXfkfQLXWzSDRSJuwnhy7szoIGmuf5sxmnNRSM6mR5+WM="

script: "mvn package"

after_success:
# encrypt -> openssl aes-256-cbc -k "pwd" -in id_rsa -out id_rsa.enc -a
# decrypt -> openssl aes-256-cbc -k "pwd" -in deploy_key.enc -d -a -out id_rsa
  - openssl aes-256-cbc -k $PASSWORD -in deploy_key.enc -d -a -out id_rsa
  - chmod 600 id_rsa
# scp copy -> scp -i ./id_rsa -o StrictHostKeyChecking=no target/tapcat-webserver.war tapcat@somehost.net:/home/tapcat/
  - scp -P 222 -i id_rsa -o StrictHostKeyChecking=no target/tapcat-webserver.war tapcat@api.tapcat.net:/home/tapcat/war/
  - ssh -p 222 -i id_rsa tapcat@api.tapcat.net 'zsh cd tapcat-deploy; git pull; ./deploy-webserver.zsh'
