language: java
jdk:
  - oraclejdk7

script: "mvn package"

after_success:
  - secure: "OvpdDxez8CCNdUtdWwOaz9F194OM1ZCMMe2W3wyECtyYGxu+FFdIg1GLfMAOUi7M+AZmi6el7kVlyB6SWLEBy7khguY2t9R1X04MGFRnZ4VAX6oYpw8lEkxx3gWiVvOsuxRzzkgUREMTBvIydtz57SPk99O7cfrcMBxtKx6Smd0="
